# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'EzKeze' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EzKeze
pod 'CryptoSwift', '~> 0.3'
pod 'TesseractOCRiOS', '4.0.0'
end

target 'Keyboard' do
  use_frameworks!
pod 'CryptoSwift', '~> 0.3'
pod 'TesseractOCRiOS', '4.0.0'
end
