# Uncomment this line to define a global platform for your project
platform :ios, '9.3'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Regular Keyboard' do
pod 'CryptoSwift', '~> 0.3'
end

target 'keyboard' do
pod 'CryptoSwift', '~> 0.3'
end

